# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempvalue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timetaken', models.DateTimeField()),
            ],
        ),
    ]
